### ISSUE TITLE
Improve docs how to use plugin

### ISSUE THREAD

**Issue by daydy16** [zalando/backstage-plugin-api-linter#23]
Thanks for your plugin! Fits perfectly in our setup!

Could you extend the docs a little bit, how to use the tabbed-layout and where to place it and the <Content>?

btw: there was a typo at https://github.com/zalando/backstage-plugin-api-linter/blob/main/README.md?plain=1#L19
package instead of package**s**
cd package**s**/app && yarn add backstage-plugin-api-linter

**Comment by natalyapeixoto** [comment]
Hi @daydy16 Thank you for feedback and pointing out the typo. 

I've fixed the typo and added the documentation for [TabbedLayout](https://backstage.io/storybook/?path=/story/navigation-tabbedlayout--default) on the readme. 

You can place it on any UI within backstage. We use it on our API catalog.
